== Allgemeines
=== rechtliche Grundlagen
Seit dem 1. Juli 2008 ist das Bundesgesetz über Geoinformation (GeoIG, SR 510.62) <<allgemeines.adoc#doc-01,[1]>> in Kraft. Am 1. Juli 2012 erfolgte die vollständige Inkraftsetzung des kantonalen Geoinformationsgesetzes (kGeoiG, SRSZ 214.110) <<allgemeines.adoc#doc-03,[3]>>. Es hat zum Ziel, verbindliche Vorgaben für die Erfassung, Modellierung und den Austausch von Geodaten festzulegen. +

Am 1. Januar 2013 trat die kantonale Verordnung über Geoinformation (kGeoiV, SRSZ 214.111) <<allgemeines.adoc#doc-04,[4]>> in Kraft. Sie präzisiert das kGeoiG in fachlicher sowie technischer Hinsicht und führt im Anhang 1 den „Katalog der Geobasisdaten des Bundesrechts mit Zuständigkeit beim Kanton“ und im Anhang 2 den „Katalog der Geobasisdaten des kantonalen Rechts“. Darin werden die Fachstellen definiert, welche für die Ausarbeitung eines Geodatenmodells zuständig sind.

=== Zweck des Dokuments
Dieses Dokument beschreibt den Geobasisdatensatz
 
* *__Bohrdaten des Bereichs "Umwelt" (A244)__.* +


Verschiedene Ämter vefügen über Informationen zu Bohrdaten und pflegen diese in je einem separaten Thema. Diese sind:

* Das Amt für Umwelt und Energie führt Bohrdaten, welche sich aus dem Umweltbereicht (z.B. Erdwärmesonden) ergeben +
-> Themennummer: A244
* Das Amt für Wald und Natur führt Bohrdaten, welche sich aus geologischen Untersuchungen ergeben +
-> Themennummer noch ausstehend
* Das Tiefbauamt führt Bohrdaten, welche sich aus der Bautätigkeit ergeben +
-> Themennummer noch ausstehend

Der Bund (swisstopo) hat dieses Thema über den Geobasisdatensatz "Archiv Bohrdaten" (ID 50.4) modelliert. Die Modelldokumentation <<allgemeines.adoc#doc-05,[5]>> ist über das https://www.geologieportal.ch/[Geologie-Portal des Bundes] einsehbar. Der Kanton Schwyz orientiert sich am Bundesmodell und erweitert dieses an wenigen Stellen.

===  Verweise auf andere Themen
Früher führte das Amt für Umwelt und Energie (AfU) Informationen in Zusammenhang mit Bohrungen im "geologischen Archiv". Dieses umfasst die "Bohrdaten" und die "Bohrprofile". Unter den "Bohrdaten" verstand man die geologischen Berichte, wohingegen die "Bohrprofile" Detailinformationen zu den einzelnen Bohrungen enthielten. Um einer Verwechslungsgefahr vorzubeugen, trennte man die beiden ähnlich klingenden Bereiche in unterschiedliche Themen und berücksichtigte, dass auch andere Ämter Informationen zu Bohrungen erfassen.

Neu sind die Informationen über geologische Berichte im Thema

* https://ch-sz-geo.github.io/A144/docs/modelldokumentation.html[geologische Berichte des Bereichs "Umwelt" (A144)]

enthalten. Spezifische Informationen über die Bohrprofile werden neu in dem hier vorliegenden Thema A244 beschrieben.

Das Themea A144 ist auf die Datenbearbeitung des AfU ausgelegt. Es dient als Vorlage für weitere Ämter, wie z.B. für das Amt für Wald und Natur, das Tiefbauamt oder das Amt für Gewässer.

=== Zielgruppen
Dieses Dokument richtet sich an folgende Nutzergruppen:

* **Fachstellen für Modellierung,** die den inhaltlichen Rahmen des Themas festlegen,
* **Datenbearbeiterinnen und -bearbeiter,** die sich über die Prozesse und Methoden der Datenpflege informieren,
* **Verantwortliche für die Datenpublikation,** die die Daten entsprechend der Freigabestufe veröffentlichen und die Transformation in andere Modelle durchführen sowie
* **Endnutzerinnen und Endnutzer,** die sich über den Inhalt und die Struktur der Daten informieren möchten.

ifdef::backend-pdf[]
<<<
endif::[]
