== Allgemeines
=== rechtliche Grundlagen
//Todo Links und Anhänge definieren 
Seit dem 1. Juli 2008 ist das https://www.fedlex.admin.ch/eli/cc/2008/388/de[Bundesgesetz über Geoinformation (GeoIG)] in Kraft. Am 1. Juli 2012
erfolgte die vollständige Inkraftsetzung des https://www.sz.ch/public/upload/assets/48275/214_110.pdf?fp=2[kantonalen Geoinformationsgesetzes (KGeoiG)]. Es hat
zum Ziel, verbindliche Vorgaben für die Erfassung, Modellierung und den Austausch von Geodaten
festzulegen. +

Am 1. Januar 2013 trat die https://www.sz.ch/public/upload/assets/5600/214_111.pdf?fp=11[kantonale Verordnung über Geoinformation (KGeoiV)] in Kraft. Sie
präzisiert das KGeoiG in fachlicher sowie technischer Hinsicht und führt im Anhang 1 „Katalog der
Geobasisdaten des Bundesrechts mit Zuständigkeit beim Kanton“ und im Anhang 2 „Katalog der
Geobasisdaten des kantonalen Rechts“. Darin werden die Fachstellen definiert, welche für die
Ausarbeitung eines Geodatenmodells zuständig sind.


===  Zweck des Dokuments
Dieses Dokument beschreibt den Geobasisdatensatz
 
* *__Bohrdaten des Bereichs "Umwelt" (A244)__.* +


Verschiedene Ämter vefügen über Informationen zu Bohrdaten und pflegen diese in je einem separaten Thema. Diese sind:

* Das Amt für Umwelt und Energie führt Bohrdaten, welche sich aus dem Umweltbereicht (z.B. Erdwärmesonden) ergeben -> A244
* Das Amt für Wald und Natur führt Bohrdaten, welche sich aus geologischen Untersuchungen ergeben -> A???
* Das Tiefbauamt führt Bohrdaten, welche sich aus der Bautätigkeit ergeben -> A???

Der Bund (swisstopo) hat dieses Thema über den Geobasisdatensatz "Archiv Bohrdaten" (ID 50.4) modelliert. Die Modelldokumentation [3] ist über das https://www.geologieportal.ch/[Geologie-Portal des Bundes] einsehbar. Der Kanton SZ orientiert sich am Bundesmodell und erweitert dieses an wenigen Stellen.

===  Verweise auf andere Themen
In allgemeiner Form sind Bohrdaten im Thema

* https://ch-sz-geo.github.io/A144/docs/modelldokumentation.html[geologische Berichte des Bereichs "Umwelt" (A144)]

beschrieben. Das Thema A144 gibt einen Überblick über alle geologischen Untersuchungen, wo hingegen das Thema A244 die spezifischen Informationen zu einzelnen Bohrungen widergibt.

Diese Dokumentation richtet sich an alle Personen, welche sich über dieses Thema informieren möchten.

ifdef::backend-pdf[]
<<<
endif::[]
